src/Entity/Creneau.php
<?php

namespace App\Entity;

use App\Repository\CreneauRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CreneauRepository::class)
 */
class Creneau
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $debutCreneau;

    /**
     * @ORM\Column(type="datetime")
     */
    private $finCreneau;

    /**
     * @ORM\ManyToOne(targetEntity=Formation::class, inversedBy="creneaux")
     */
    private $Formation;

    /**
     * @ORM\ManyToOne(targetEntity=Place::class, inversedBy="creneaux")
     */
    private $Place;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDebutCreneau(): ?\DateTimeInterface
    {
        return $this->debutCreneau;
    }

    public function setDebutCreneau(\DateTimeInterface $debutCreneau): self
    {
        $this->debutCreneau = $debutCreneau;

        return $this;
    }

    public function getFinCreneau(): ?\DateTimeInterface
    {
        return $this->finCreneau;
    }

    public function setFinCreneau(\DateTimeInterface $finCreneau): self
    {
        $this->finCreneau = $finCreneau;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->Formation;
    }

    public function setFormation(?Formation $Formation): self
    {
        $this->Formation = $Formation;

        return $this;
    }

    public function getPlace(): ?Place
    {
        return $this->Place;
    }

    public function setPlace(?Place $Place): self
    {
        $this->Place = $Place;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Creneau;
use App\Form\CreneauType;
use App\Form\NouveauCreneauType;
use App\Repository\PlaceRepository;
use App\Repository\SalleRepository;
use App\Repository\CreneauRepository;
use App\Repository\FormationRepository;
use App\Repository\StagiaireRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home", methods={"GET","POST"})
     */
    public function index(FormationRepository $formationRepository, SalleRepository $salleRepository, StagiaireRepository $stagiaireRepository, PlaceRepository $placeRepository, CreneauRepository $creneauRepository,Request $request): Response
    {
        $creneau = new Creneau();
        $form = $this->createForm(NouveauCreneauType::class, $creneau);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($creneau);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'formations' => $formationRepository->findAll(),
            'salles' => $salleRepository->findAll(),
            'stagiaires' => $stagiaireRepository->findAll(),
            'places' => $placeRepository->findAll(),
            'creneaux' => $creneauRepository->findAll(),
            'creneau' => $creneau,
            'form' => $form->createView(),
        ]);
    }

    /**
    * @Route("creneau/{id}/nouveau", name="nouveau-creneau", methods={"GET","POST"})) 
    */
    // public function nouveauCreneau(Request $request): Response
    // {
    //     $creneau = new Creneau();
    //     $form = $this->createForm(CreneauType::class, $creneau);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $entityManager = $this->getDoctrine()->getManager();
    //         $entityManager->persist($creneau);
    //         $entityManager->flush();

    //         return $this->redirectToRoute('home');
    //     }

    //     return $this->render('home/index.html.twig', [
    //         'creneau' => $creneau,
    //         'form' => $form->createView(),
    //     ]);
    // }
}

templates/home/_nouveauCreneau.html.twig
{{ form_start(form) }}

        {{ form_widget(form.debutCreneau, { 'label': 'Début du créneau' }) }}
        {{ form_widget(form.finCreneau, { 'label': 'Fin du créneau' }) }}
        {{ form_widget(form.Formation, { 'label': 'Formation' }) }} 
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}


{# , {'action': path('nouveau-creneau', { 'id': place.id })} #}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'Accueil - Intrarinfo{% endblock %}

{% block body %}
<div>
  <p>Objectifs et difficultés:</p>
  <ul>
    <li>Cliquer sur une ligne de la chronologie doit renvoyer vers un <b>formulaire en pop-up</b>.</li>
    <li>Le lien doit renvoyer vers un <b>nouveau créneau.</b></li>
    <li>Le nouveau créneau doit être affilié à la <b>ligne correspondante.</b></li>
    <li><b>L'envergure de la chronologie</b> doit être adaptée et non soumise aux créneaux enregistrés (Défilement horizontal ?).(en cours)</li>
    <li>Possibilité de <b>mettre en valeur certaines dates</b> ? Par exemple la date du jour ? (valide)</li>
  </ul>
</div>

    {% for salle in salles %}
    <script type="text/javascript">


      //Pour chaque salle on crèe une chronologie ("timeline")
      google.charts.load("current", {packages:["timeline"], 'language': 'fr'});
      google.charts.setOnLoadCallback(drawChart);
      
      //On utilise moment.js pour définir l'envergure de la chronologie
      var debutChrono = moment();
        debutChrono.subtract(2, 'months');
        debutChrono.format('Y, M, D');

      var finChrono = moment();
        finChrono.add(2, 'months');
        finChrono.format('Y, M, D');



        function drawChart() {
    
          var container = document.getElementById('salle{{ salle.id }}');
          var chart = new google.visualization.Timeline(container);
          var dataTable = new google.visualization.DataTable();
          //Le 1er élément sera le nom de la place
          dataTable.addColumn({ type: 'string', id: 'Place' });
          //Le nom du stagiaire concerné est affiché sur la bande du créneau
          dataTable.addColumn({ type: 'string', id: 'Stagiaire' });
          //Date de début du créneau
          dataTable.addColumn({ type: 'date', id: 'Début' });
          //Date de fin du créneau
          dataTable.addColumn({ type: 'date', id: 'Fin' });
          //On injecte les données
          dataTable.addRows([



          {% for stagiaire in stagiaires %}



            {% for creneau in creneaux %}
              {% if creneau.place == stagiaire.place %}
                {% if salle.id == stagiaire.place.salle.id %}
                  [ '{{ stagiaire.place.nomPlace }}', '{{ stagiaire.prenomStagiaire }} {{ stagiaire.nomStagiaire }}', 
                  new Date({{ creneau.debutCreneau|date('Y, m, d') }}), new Date({{ creneau.finCreneau|date('Y, m, d') }}) ],
                {% endif %}

              {% endif %}

            {% endfor %}
          {% endfor %}

          ["\0", "Aujourd'hui", new Date(), new Date() ],
  
          ]);
          
          // Create a range slider, passing some options
        var envergure = new google.visualization.ControlWrapper({
          'controlType': 'ChartRangeFilter',
          'state': {"range": {"start": debutChrono, "end": finChrono} }

        });

          
          var options = {
            //Couleurs des créneaux
            colors: [
            {% for creneau in creneaux %}
              '{{ creneau.formation.couleurFormation }}',
            {% endfor %}
            ],
            //On fixe le début et la fin de la chronologie en utilisant les variables définie grâce à moment.js
            hAxis: {
              minValue: new Date(debutChrono),  
              maxValue: new Date(finChrono)
            },
          };

          //On précise qu'on active les options : ",options", et on dessine le tableau.
          chart.draw(dataTable, options, envergure, {
            width: 2000
          });


        }

  
  
    </script>
    {% endfor %}
    <script>
      //On charge le document
      $(document).ready(function(){


        setTimeout(function(){ 


          //Pour chaque salle                   
          {% for salle in salles %}
            //Dans un tableau on commence à compter à 0
            {% set count = -1 %}
              //Pour chaque place dans la salle
              {% for place in places %}
                //Si la la place est bien dans la salle
                {% if salle.id == place.salle.id %}
                  {% set count = count + 1 %}
                    //On différencie chaque ligne du tableau
                    truc = $('#salle{{ salle.id }} rect:eq({{count}})');
                    //On ajoute au "rect" des attributs pour le système de modaux
                    truc.attr('data-toggle', 'modal');
                    truc.attr('data-target', 'modal{{ place.id }}');
                    truc.attr('type', 'button');
                    truc.addClass('btn');
                    //
                    truc.click(function(){
                      $('#modal{{ place.id }}').modal("show");
                    });
                {% endif %}
              {% endfor %}
            


          {% endfor %}

        }, 3000);
      });

    </script>

    {% for place in places %}
      <!-- Vertically centered modal -->
      <div class="modal fade" id="modal{{ place.id }}" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Nouveau Créneau pour la place {{ place.nomPlace }}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              {{ form_start(form) }}
                {{ form_widget(form.debutCreneau, { 'label': 'Début du créneau' }) }}
                {{ form_widget(form.finCreneau, { 'label': 'Fin du créneau' }) }}
                {{ form_widget(form.Formation, { 'label': 'Formation' }) }} 
              
              {# {{ include('creneau/_form.html.twig') }}  #}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
              <button type="button" class="btn btn-primary">Enregistrer</button>
              {{ form_end(form) }}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}


  
<div class="chronos">
  {% for salle in salles %}
  <h3>{{ salle.nomSalle }}</h3>
  <div class="chrono" id="salle{{ salle.id }}" style="height: 300px;"></div>
  {% endfor %}
</div>


{% endblock %}